FROM python:3.12-slim-bookworm

# Install system packages
RUN apt-get update --yes --quiet && apt-get install --yes --quiet --no-install-recommends \
    build-essential \
    libpq-dev \
    libmariadb-dev \
    libjpeg62-turbo-dev \
    zlib1g-dev \
    libwebp-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install requirements
COPY requirements.txt /
RUN pip install -r /requirements.txt

# Setup app
WORKDIR /app
RUN useradd wagtail
RUN chown wagtail:wagtail /app

# Copy project
COPY --chown=wagtail:wagtail . .

# Copy GCP Key for Dev
COPY gcp-key.json /tmp/gcp-auth/key.json
RUN chmod 644 /tmp/gcp-auth/key.json && chown wagtail:wagtail /tmp/gcp-auth/key.json

USER wagtail
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
