# Generated by Django 5.2.6 on 2025-10-01 04:52

from django.db import migrations


def set_created_by_from_owner(apps, schema_editor):
    """
    Set created_by field to match owner field for existing quizzes
    """
    Quiz = apps.get_model('quiz', 'Quiz')
    
    for quiz in Quiz.objects.all():
        if quiz.owner_id and not quiz.created_by_id:
            quiz.created_by_id = quiz.owner_id
            quiz.save(update_fields=['created_by'])


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - clear created_by field
    """
    Quiz = apps.get_model('quiz', 'Quiz')
    Quiz.objects.all().update(created_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_created_by'),
    ]

    operations = [
        migrations.RunPython(set_created_by_from_owner, reverse_migration),
    ]
