# Generated by Django 5.2.6 on 2025-10-01 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_set_created_by_from_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='auto_submit_on_violations',
            field=models.BooleanField(default=False, help_text='Automatically submit quiz when violation limit is reached'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='disable_copy_paste',
            field=models.BooleanField(default=False, help_text='Disable copy and paste during quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='disable_right_click',
            field=models.BooleanField(default=False, help_text='Disable right-click context menu during quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='enable_fullscreen',
            field=models.BooleanField(default=False, help_text='Require fullscreen mode during quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_tab_switches',
            field=models.IntegerField(default=3, help_text='Maximum allowed tab switches (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='quiz',
            name='monitor_tab_switching',
            field=models.BooleanField(default=False, help_text='Monitor and count tab switches during quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='prevent_browser_back',
            field=models.BooleanField(default=False, help_text='Prevent using browser back button during quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_options',
            field=models.BooleanField(default=False, help_text='Shuffle answer options for each question'),
        ),
    ]
