# Generated by Django 5.2.8 on 2025-11-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_auto_submit_on_violations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrollment_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone',
        ),
    ]
