# Generated by Django 5.2.8 on 2025-11-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='auto_submit_on_violations',
            field=models.BooleanField(default=True, help_text='Automatically submit quiz when violation limit is reached'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='disable_copy_paste',
            field=models.BooleanField(default=True, help_text='Disable copy and paste during quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='disable_right_click',
            field=models.BooleanField(default=True, help_text='Disable right-click context menu during quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='enable_fullscreen',
            field=models.BooleanField(default=True, help_text='Require fullscreen mode during quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='monitor_tab_switching',
            field=models.BooleanField(default=True, help_text='Monitor and count tab switches during quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='prevent_browser_back',
            field=models.BooleanField(default=True, help_text='Prevent using browser back button during quiz'),
        ),
    ]
