// Security settings from server - PLACEHOLDER - DO NOT EDIT
const SECURITY = {
  monitorTabSwitching: MONITOR_TAB_SWITCHING_PLACEHOLDER,
  maxTabSwitches: MAX_TAB_SWITCHES_PLACEHOLDER,
  autoSubmitOnViolations: AUTO_SUBMIT_ON_VIOLATIONS_PLACEHOLDER,
  enableFullscreen: ENABLE_FULLSCREEN_PLACEHOLDER,
  disableRightClick: DISABLE_RIGHT_CLICK_PLACEHOLDER,
  disableCopyPaste: DISABLE_COPY_PASTE_PLACEHOLDER,
  preventBrowserBack: PREVENT_BROWSER_BACK_PLACEHOLDER
};
