# Generated by Django 5.2.6 on 2025-09-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_institute_remove_userprofile_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, choices=[('btech', 'BTech (4 years)'), ('mtech', 'MTech (2 years)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_admission',
            field=models.PositiveIntegerField(blank=True, help_text='Year when the student was admitted', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
